### ISSUE TITLE
[Bug] - cannot import name 'tokenize_13a' from 'sacrebleu'

### ISSUE THREAD

**Issue by DiegoMoussallem** [facebookresearch/vizseq#29]
# 🐛 Bug

I just followed the installation steps and got this error. 

## To reproduce

** Minimal Code/Config snippet to reproduce **

** Stack trace/error message **
```
(base) diegomoussallem@Diegos-MBP examples % python -m vizseq.server --port 9001 --data-root examples/data
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/diegomoussallem/Desktop/vizseq/vizseq/__init__.py", line 15, in <module>
    from vizseq.ipynb import *
  File "/Users/diegomoussallem/Desktop/vizseq/vizseq/ipynb/__init__.py", line 8, in <module>
    from .core import (view_examples, view_n_grams, view_stats, view_scores,
  File "/Users/diegomoussallem/Desktop/vizseq/vizseq/ipynb/core.py", line 15, in <module>
    from vizseq._data import (VizSeqDataSources, PathOrPathsOrDictOfStrList,
  File "/Users/diegomoussallem/Desktop/vizseq/vizseq/_data/__init__.py", line 14, in <module>
    from .config_manager import VizSeqTaskConfigManager, VizSeqGlobalConfigManager
  File "/Users/diegomoussallem/Desktop/vizseq/vizseq/_data/config_manager.py", line 13, in <module>
    from .tokenizers import VizSeqTokenization
  File "/Users/diegomoussallem/Desktop/vizseq/vizseq/_data/tokenizers.py", line 10, in <module>
    from sacrebleu import tokenize_13a, tokenize_v14_international, tokenize_zh
ImportError: cannot import name 'tokenize_13a' from 'sacrebleu' (/opt/anaconda3/lib/python3.7/site-packages/sacrebleu/__init__.py)
```

## System information
- 
- 
-

**Comment by madKuchenbaecker** [comment]
i got the same issue. `pip install sacrebleu=="1.4.5" ` fixed it for me quick and dirty.

**Comment by DiegoMoussallem** [comment]
thank you, so, let's suggest it at -> https://github.com/facebookresearch/vizseq/blob/master/setup.py#L45

**Comment by rachida-ly** [comment]
j'ai obtenu l'erreur 

ImportError                               Traceback (most recent call last)
<ipython-input-1-8bd1dbd9b2de> in <module>
      4 import pickle
      5 from sumeval.metrics.rouge import RougeCalculator
----> 6 from sumeval.metrics.bleu import BLEUCalculator
      7 from hyperdash import Experiment
      8 

~\Desktop\FOLDER3\sumeval\metrics\bleu.py in <module>
----> 1 from sacrebleu import corpus_bleu, TOKENIZERS, DEFAULT_TOKENIZER
      2 from sumeval.metrics.lang import get_lang
      3 
      4 
      5 class BLEUCalculator():

ImportError: cannot import name 'DEFAULT_TOKENIZER' from 'sacrebleu' (C:\Users\21267\Desktop\FOLDER3\sacrebleu\__init__.py)

**Comment by kahne** [comment]
@DiegoMoussallem @madKuchenbaecker Thank you very much for reporting this issue! This bug should be fixed by #32 now.

**Comment by hsiang-lee** [comment]
I got a similar err.

Traceback (most recent call last):
  File "C:\Users\leehsiang\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\leehsiang\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\projects\CodeGen\codegen_sources\model\translate.py", line 19, in <module>
    from codegen_sources.preprocessing.lang_processors.cpp_processor import CppProcessor
  File "D:\projects\CodeGen\codegen_sources\preprocessing\lang_processors\cpp_processor.py", line 7, in <module>
    from codegen_sources.preprocessing.lang_processors.tree_sitter_processor import (
  File "D:\projects\CodeGen\codegen_sources\preprocessing\lang_processors\tree_sitter_processor.py", line 8, in <module>
    from codegen_sources.preprocessing.lang_processors.tokenization_utils import (
  File "D:\projects\CodeGen\codegen_sources\preprocessing\lang_processors\tokenization_utils.py", line 8, in <module>
    from sacrebleu import tokenize_v14_international
ImportError: cannot import name 'tokenize_v14_international' from 'sacrebleu' (C:\Users\leehsiang\AppData\Local\Programs\Python\Python39\lib\site-packages\sacrebleu\__init__.py)

"tokenize_v14_international" cannot be imported, rather than "tokenize_13a". I run "pip install --upgrade vizseq". But error still exists.

Anybody could help me?

**Comment by heychhavi** [comment]
@kahne 
ImportError: cannot import name 'Tokenizer13a' from 'sacrebleu.tokenizers' ...still getting the error even after upgrading vizseq 
can you suggest solution for this?
